#ifndef PANELSTATS_H
#define PANELSTATS_H
#include <atomic>
#include <cstdint>

// Render-pipeline counters for "the UI runs but the picture lags" diagnosis. Producers are the UI task (frames), the
// LVGL flush callback (copies into the PSRAM framebuffer) and the RGB panel's VSYNC interrupt; the consumer is
// WebUIPlugin, which snapshots them every 10 s for a serial line and for GET /api/ota. Lock-free by design so the
// ISR producer never blocks.
struct PanelStats {
    std::atomic<uint32_t> uiFrames{0};     // DefaultUI::loop() iterations
    std::atomic<uint32_t> flushes{0};      // LVGL flush callbacks
    std::atomic<uint32_t> flushUsTotal{0}; // time spent inside flush, microseconds
    std::atomic<uint32_t> flushUsMax{0};
    std::atomic<uint32_t> vsyncs{0};     // RGB panel VSYNC interrupts (nominal ~23.5 Hz on the T-RGB)
    std::atomic<uint32_t> vsyncsLate{0}; // VSYNCs that arrived > 1.5 periods after the previous one: the ISR itself was held off
    std::atomic<uint32_t> frameCompletes{0}; // frames the RGB DMA finished fetching before the driver's VSYNC reset
    std::atomic<int64_t> lastVsyncUs{0};

    struct Snapshot {
        float uiFps = 0, flushHz = 0, vsyncHz = 0;
        uint32_t flushAvgUs = 0, flushMaxUs = 0, vsyncsLate = 0;
        uint32_t underruns = 0; // vsyncs - frameCompletes: frames shown with stale or shifted pixels (visible tearing)
    };

    // ISR-safe: one atomic exchange and one compare. The panel's timing is generated by the LCD peripheral, so a late
    // VSYNC only says the interrupt was delayed (a flash write with the cache off, a long critical section). It does
    // not see the DMA falling behind the pixel clock; that is what `underruns` is for.
    void recordVsync(int64_t nowUs, int64_t latePeriodUs) {
        const int64_t prev = lastVsyncUs.exchange(nowUs, std::memory_order_relaxed);
        vsyncs.fetch_add(1, std::memory_order_relaxed);
        if (prev != 0 && nowUs - prev > latePeriodUs)
            vsyncsLate.fetch_add(1, std::memory_order_relaxed);
    }

    // ISR-safe. CONFIG_LCD_RGB_RESTART_IN_VSYNC resets the DMA at every VSYNC; a frame whose descriptors the DMA did
    // not finish before that reset never wraps its link, so the driver never reports it complete. The deficit against
    // the VSYNC count is the number of frames the panel showed while starved (PSRAM contention or a flash fetch
    // hogging the same SPI bus).
    void recordFrameComplete() { frameCompletes.fetch_add(1, std::memory_order_relaxed); }

    void recordFlush(uint32_t us) {
        flushes.fetch_add(1, std::memory_order_relaxed);
        flushUsTotal.fetch_add(us, std::memory_order_relaxed);
        uint32_t prev = flushUsMax.load(std::memory_order_relaxed);
        while (us > prev && !flushUsMax.compare_exchange_weak(prev, us, std::memory_order_relaxed)) {
        }
    }

    // Rates over the window since the previous snapshot; resets the counters.
    Snapshot snapshot(uint32_t elapsedMs) {
        Snapshot s;
        const uint32_t frames = uiFrames.exchange(0), fl = flushes.exchange(0), total = flushUsTotal.exchange(0),
                       mx = flushUsMax.exchange(0), vs = vsyncs.exchange(0), late = vsyncsLate.exchange(0),
                       fc = frameCompletes.exchange(0);
        if (elapsedMs == 0)
            return s;
        const float sec = elapsedMs / 1000.0f;
        s.uiFps = frames / sec;
        s.flushHz = fl / sec;
        s.vsyncHz = vs / sec;
        s.flushAvgUs = fl ? total / fl : 0;
        s.flushMaxUs = mx;
        s.vsyncsLate = late;
        s.underruns = vs > fc ? vs - fc : 0;
        return s;
    }
};

inline PanelStats &panelStats() {
    static PanelStats stats;
    return stats;
}

#endif // PANELSTATS_H
