#!/usr/bin/env -S uv run --script --with pillow
# /// script
# dependencies = ["pillow"]
# ///
"""Convert a PNG into the LVGL 8 C image file EEZ Studio would generate.

The device UI under src/display/ui/default/eez/ is generated by EEZ Studio from
eez-ui/gaggimate.eez-project, which embeds every bitmap as a base64 PNG. Swapping
a bitmap therefore means (a) replacing that PNG in the project and (b)
regenerating the matching images/ui_image_<name>.c. EEZ Studio does (b) on
export; this script does the same thing from the command line so a bitmap swap
needs no GUI. Output has been confirmed identical (modulo whitespace) to EEZ's
own converter for every bitmap in the project (see --check).

Emits LV_IMG_CF_TRUE_COLOR_ALPHA with the four LV_COLOR_DEPTH blocks EEZ writes,
one byte per line. The display build uses LV_COLOR_DEPTH 16, no swap.

Two quirks of EEZ's converter are reproduced deliberately, because a bitmap
swap should not also silently change every other pixel:

- Channels are rounded to the nearest representable level (lv_img_conv's
  classify_pixel), not truncated.
- EEZ reads the PNG through an HTML canvas, i.e. premultiplied alpha. Fully
  transparent pixels come back with RGB 0 whatever the file says, and
  semi-transparent ones are perturbed by the premultiply/unpremultiply round
  trip. Without this, 3 of the 36 bitmaps differ.

    scripts/lvgl_img.py logo.png img_logo src/display/ui/default/eez/images/ui_image_logo.c
    scripts/lvgl_img.py --check logo.png img_logo src/display/ui/default/eez/images/ui_image_logo.c
"""

import argparse
import sys

from PIL import Image

HEADER = """#ifdef __has_include
#if __has_include("lvgl.h")
#ifndef LV_LVGL_H_INCLUDE_SIMPLE
#define LV_LVGL_H_INCLUDE_SIMPLE
#endif
#endif
#endif
#ifdef __has_include
#if __has_include("lvgl.h")
#ifndef LV_LVGL_H_INCLUDE_SIMPLE
#define LV_LVGL_H_INCLUDE_SIMPLE
#endif
#endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMG_{SYM}
#define LV_ATTRIBUTE_IMG_{SYM}
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_{SYM} uint8_t {sym}_map[] = {{
"""

FOOTER = """}};

const lv_img_dsc_t {sym} = {{
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {w},
    .header.h = {h},
    .data_size = {n} * LV_IMG_PX_SIZE_ALPHA_BYTE,
    .data = {sym}_map,
}};"""


def quantize(value, bits):
    """Round a channel to its nearest `bits`-bit level, as lv_img_conv's classify_pixel does.

    Round-half-up, not truncation: 236 at 5 bits is 30 (0xF0), not 29 (0xE8).
    Truncating matched EEZ on 48 of the 112 pixels of indicator-small; this
    matches all 112. The top level saturates (0xF8 / 0xFC) rather than wrapping.
    lv_img_conv applies the same classify_pixel to the 3-3-2 block; the repo's
    bitmaps are pure black there, so --check cannot exercise that path.
    """
    step = 1 << (8 - bits)
    return min(int(value / step + 0.5) * step, 255 - (step - 1))


def canvas_roundtrip(c, a):
    """What a browser canvas hands back for channel `c` at alpha `a`.

    Canvases store premultiplied 8-bit colour, so getImageData() returns
    round(round(c * a / 255) * 255 / a) -- and 0 when a == 0, where the colour is
    simply gone. Skia's integer premultiply equals round(c * a / 255) for every
    input; its table-driven unpremultiply and the float form agree on every
    pixel in this project, so the simpler float form is used.
    """
    if a == 0:
        return 0
    premultiplied = int(c * a / 255 + 0.5)
    return int(premultiplied * 255 / a + 0.5)


def blocks(pixels):
    """Yield (guard, comment, bytes) for each colour-depth block, in EEZ's order."""
    c8, c16, c16s, c32 = bytearray(), bytearray(), bytearray(), bytearray()
    for r, g, b, a in pixels:
        r, g, b = canvas_roundtrip(r, a), canvas_roundtrip(g, a), canvas_roundtrip(b, a)
        c8 += bytes((quantize(r, 3) | (quantize(g, 3) >> 3) | (quantize(b, 2) >> 6), a))
        r5, g6, b5 = quantize(r, 5), quantize(g, 6), quantize(b, 5)
        rgb565 = (r5 << 8) | (g6 << 3) | (b5 >> 3)
        c16 += bytes((rgb565 & 0xFF, rgb565 >> 8, a))
        c16s += bytes((rgb565 >> 8, rgb565 & 0xFF, a))
        c32 += bytes((b, g, r, a))
    yield ("LV_COLOR_DEPTH == 1 || LV_COLOR_DEPTH == 8",
           "/*Pixel format: Alpha 8 bit, Red: 3 bit, Green: 3 bit, Blue: 2 bit*/", c8)
    yield ("LV_COLOR_DEPTH == 16 && LV_COLOR_16_SWAP == 0",
           "/*Pixel format: Alpha 8 bit, Red: 5 bit, Green: 6 bit, Blue: 5 bit*/", c16)
    yield ("LV_COLOR_DEPTH == 16 && LV_COLOR_16_SWAP != 0",
           "/*Pixel format: Alpha 8 bit, Red: 5 bit, Green: 6 bit, Blue: 5 bit  BUT the 2  color bytes are swapped*/", c16s)
    yield ("LV_COLOR_DEPTH == 32", None, c32)


def convert(png_path, sym):
    im = Image.open(png_path).convert("RGBA")
    w, h = im.size
    raw = im.tobytes()
    pixels = (raw[i:i + 4] for i in range(0, len(raw), 4))
    out = [HEADER.format(sym=sym, SYM=sym.upper())]
    for guard, comment, data in blocks(pixels):
        out.append("#if %s\n" % guard)
        if comment:
            out.append("    %s\n" % comment)
        out.append("".join("    0x%02x,\n" % v for v in data))
        out.append("#endif\n")
    out.append(FOOTER.format(sym=sym, w=w, h=h, n=w * h))
    return "".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("png")
    ap.add_argument("symbol", help="C symbol, e.g. img_logo")
    ap.add_argument("out", help="path of the .c file to write (or compare against)")
    ap.add_argument("--check", action="store_true", help="compare against an existing file instead of writing")
    args = ap.parse_args()

    text = convert(args.png, args.symbol)
    if args.check:
        with open(args.out) as f:
            existing = f.read()
        # Some generated files have since been clang-formatted (wrapped
        # declarations, different indentation, several bytes per line), so compare
        # the token stream rather than the bytes.
        if "".join(existing.split()) == "".join(text.split()):
            print("identical: %s" % args.out)
            return 0
        print("DIFFERS: %s (%d vs %d bytes)" % (args.out, len(existing), len(text)))
        return 1
    with open(args.out, "w") as f:
        f.write(text)
    print("wrote %s (%dx%d)" % (args.out, *Image.open(args.png).size))
    return 0


if __name__ == "__main__":
    sys.exit(main())
